//
//  Timetable.swift
//  HEG Schedule
//
//  Created by Dietrich Poensgen on 14.06.21.
//

import Foundation

// MARK: Model of the timetables (Vertretungspläne). This is based on the json objects that are generated by the api server
struct Timetable: Codable, Identifiable {
    var id = UUID()
    let title: String
    let url: String
    let date: String
    let preview: String
    let secondTitle: String
}
